added checks for LE-01,2,4 and changes in graphql
eddie-knight/pvtr-osps-baseline pull request #23
Opened 2024-12-22 00:07 UTC by vpavankalyan

added checks for LE-01,2,4 and changes in graphql

2024-12-22 03:57 UTC, eddie-knight requested changes
Looking good! Left some notes.

2024-12-22 03:57 UTC, eddie-knight commented on armory/le-01.go
> +		Description: "Inspect Org & Repo Policy to Enforce Web SignOff",
```suggestion
		Description: "Inspect Org & Repo Policy to Ensure Web SignOff is Enabled",
```

2024-12-22 03:57 UTC, eddie-knight commented on armory/le-04.go
> +	approvedLicenses := []string{
What's the difference between this list and the one above?

2024-12-22 03:57 UTC, eddie-knight commented on armory/le-04.go
> +	license := Data.GraphQL().Repository.LicenseInfo.Name
We might want to split this one off into a separate PR... The check here needs to inspect the release artifacts to determine whether a secondary license has been included separate from the one in the source repo.

2024-12-22 10:50 UTC, vpavankalyan commented on armory/le-04.go
> +	approvedLicenses := []string{
I am making sure the License of the repo is one of the standard licenses.

2024-12-22 14:58 UTC, eddie-knight commented on armory/le-04.go
> +	approvedLicenses := []string{
The different lists might be a moot point anyhow, since LE_04 is for the release, not the repo

2025-01-04 15:08 UTC, eddie-knight commented
Hey @vpavankalyan it looks like this PR has gotten a bit wily on you.

Would you be happy to close this PR and make the changes in a new PR?

It'll also help with the review/merge process if you could make one PR per "test suite," like in #33, #34, etc.

2025-01-04 15:29 UTC, closed without merging